Fail CMake configure for unsupported GCC 7
Building with GCC 7 fails with the following compilation error:

    ../src/./quick-lint-js/parse.h:229:35: sorry, unimplemented: non-trivial designated initializers not supported
                 this->parse_expression(precedence{.in_operator = true});
                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Make CMake configuration fail (instead of having compilation fail),
producing a hopefully more helpful error message.