Fix regression in command line option parsing
quick-lint-js interprets the following command incorrectly, leading to
an unexcepted error:

    $ ./build-clang-stage3/src/quick-lint-js --output-format vim-qflist-json --vim-file-bufnr 3 jquery-3.5.1.js
    error: unrecognized option: 3

Fix the error by fixing a tiny mistake in the option parser.