Fix compilation with weird compiler setups
A contributor tried to build quick-lint-js. They had both GCC 7 and GCC
8 installed. Confusingly, the 'cc' command referred to GCC 7 and the
'c++' command referred to GCC 8. This caused linking problems:

    [100%] Linking CXX executable quick-lint-js-test
    CMakeFiles/quick-lint-js-test.dir/test-file.cpp.o: In function `quick_lint_js::(anonymous namespace)::make_temporary_directory()':
    test-file.cpp:(.text+0x1aa1): undefined reference to `std::filesystem::temp_directory_path[abi:cxx11]()'
    CMakeFiles/quick-lint-js-test.dir/test-file.cpp.o: In function `std::filesystem::__cxx11::path::path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::filesystem::__cxx11::path::format)':
    test-file.cpp:(.text._ZNSt10filesystem7__cxx114pathC2EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS1_6formatE[_ZNSt10filesystem7__cxx114pathC5EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS1_6formatE]+0x4f): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
    [snip]

Work around these problems with an ugly hack in CMake. For normal
setups, this hack shouldn't cause problems (but it certainly could).