fix(test): fix wrong #include on FreeBSD
We need to #include <libutil.h> for forkpty() in a few test files.
However, we included <util.h> instead by mistake, causing build failures
on FreeBSD:

    [snip]/test-cli.cpp:17:10: fatal error: 'util.h' file not found

Fix the included path, fixing the FreeBSD build.

Co-Authored-By: Nico Sonack <nsonack@herrhotzenplotz.de>