Improve reporting of "\u{00a0:"
Given following program, quick-lint-js reports crappy diagnostics
because \u parsing extends to the end of the file:

    // hello.js:4:2: error: unclosed identifier escape sequence [E0038]
    // hello.js:4:1: error: unclosed string literal [E0040]

    "\u{00a0:"

Fix this by stopping \u parsing when a non-identifier character is
encountered:

    // hello.js:3:2: error: unclosed identifier escape sequence [E0038]

    "\u{00a0:"

This lets us document E0038 more easily.

This commit changes the error recovery behavior of sequences such as
\u{-0020}. This commit also changes diagnostics for sequences such as
"\u{2642 ".