fix(ci): fix duplicate artifact names
Different GitHub artifacts in the same workflow cannot have the same name. Since
upgrading to v4, we're getting errors because of this:

> Error: Failed to CreateArtifact: Received non-retryable error: Failed request:
> (409) Conflict: an artifact with this name already exists on the workflow run

Rename the artifacts in the test-vim-plugin workflow so that they're distinct
from each other.