fix(arch): refresh update-aur.sh GPG keys; fix builds
update-aur.sh is failing to install Arch Linux system packages:

    :: Retrieving packages...
     gcc-12.2.1-1-x86_64 downloading...
     gcc-libs-12.2.1-1-x86_64 downloading...
     cmake-3.25.2-1-x86_64 downloading...
     libisl-0.25-1-x86_64 downloading...
     libuv-1.44.2-1-x86_64 downloading...
     rhash-1.4.3-1-x86_64 downloading...
     jsoncpp-1.9.5-2-x86_64 downloading...
     ninja-1.11.1-2-x86_64 downloading...
     libmpc-1.3.1-1-x86_64 downloading...
     libnsl-2.0.0-2-x86_64 downloading...
    checking keyring...
    checking package integrity...
    error: gcc-libs: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
    :: File /var/cache/pacman/pkg/gcc-libs-12.2.1-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
    Do you want to delete it? [Y/n]
    error: libisl: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
    :: File /var/cache/pacman/pkg/libisl-0.25-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
    Do you want to delete it? [Y/n]
    error: gcc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
    :: File /var/cache/pacman/pkg/gcc-12.2.1-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
    Do you want to delete it? [Y/n]
    error: ninja: signature from "kpcyrd <git@rxv.cc>" is unknown trust
    :: File /var/cache/pacman/pkg/ninja-1.11.1-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
    Do you want to delete it? [Y/n]
    error: failed to commit transaction (invalid or corrupted package (PGP signature))
    Errors occurred, no packages were upgraded.
    ==> ERROR: 'pacman' failed to install missing dependencies.
    ==> Missing dependencies:
      -> cmake
      -> gcc
      -> ninja
    ==> ERROR: Could not resolve all dependencies.

Update our Arch Linux Docker container to fix these issues.