fix(test): add missing #include
Fix no-PCH builds failing with the following error:

    In file included from test/test-async-byte-queue.cpp:16:
    test/./quick-lint-js/tracking-memory-resource.h:49:32: error: no member named 'new_delete_resource' in namespace 'boost::container::pmr'
          ::boost::container::pmr::new_delete_resource();
          ~~~~~~~~~~~~~~~~~~~~~~~~~^
    1 error generated.