fix(vscode): work around test flakiness on Windows
We test our Visual Studio Code extension with VS Code version 1.49.0.
This version reliably causes test failures on my machine with the
following message:

    [snip]
    OK      enabling then disabling then enabling logging reuses output channel
    Exit code:   0
    Done

    Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\strager\AppData\Local\Temp\5NN6h7\logs\20230821T201653\exthost1\exthost.log'
	at unlinkSync (node:fs:1860:3)
	at _unlinkSync (node:internal/fs/rimraf:214:14)
	at rimrafSync (node:internal/fs/rimraf:195:7)
	at node:internal/fs/rimraf:253:9
	at Array.forEach (<anonymous>)
	at _rmdirSync (node:internal/fs/rimraf:250:7)
	at rimrafSync (node:internal/fs/rimraf:193:7)
	at node:internal/fs/rimraf:253:9
	at Array.forEach (<anonymous>)
	at _rmdirSync (node:internal/fs/rimraf:250:7)
    error Command failed with exit code 1.

Work around this issue by upgrading VS Code to a better-working version.
I could not find any upstream patches or change notes mentioning the
fix, so maybe the upstream fix was accidental. *shrug*