Prevent integer overflow when reading input file
Feeding quick-lint-js over 2 GiB of source through a pipe causes
quick-lint-js to overflow 'int' and eventually crash:

    $ yes "$(printf '%4096s' '')" | ./build-debug/quick-lint-js /dev/stdin
    ../src/file.cpp:79:24: runtime error: signed integer overflow: 2147480114 + 4096 cannot be represented in type 'int'
    ../src/./quick-lint-js/narrow-cast.h:84: internal check failed in narrow_cast: in_range<Out>(x)
    zsh: broken pipe                                 yes "$(printf '%4096s' '')" |
    zsh: illegal hardware instruction (core dumped)  ./build-debug/quick-lint-js /dev/stdin

Fix the overflow and the crash by telling the user about the problem
nicely:

    $ yes "$(printf '%4096s' '')" | ./build-debug/quick-lint-js /dev/stdin
    error: file too large to read into memory