Disable char8_t on broken compilers
On some compilers, notably Clang with Xcode Command Line Tools on macOS
10.14, using char8_t can cause linker failures. For example:

    Undefined symbols for architecture x86_64:
      "__ZTIDu", referenced from:
          __ZN7testing8internal11GetTypeNameIKDuEENSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEv in test-parse.cpp.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Disable char8_t on these compilers.