fix(arch): fix GnuPG issues during AUR update
Installing packages with ghcr.io/quick-lint/quick-lint-js-dist-arch:v8
fails:

    error: rhash: signature from "Johannes Löthberg <johannes@kyriasis.com>" is unknown trust
    :: File /var/cache/pacman/pkg/rhash-1.4.4-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
    Do you want to delete it? [Y/n]
    error: libisl: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
    :: File /var/cache/pacman/pkg/libisl-0.26-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
    Do you want to delete it? [Y/n]
    error: gcc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
    :: File /var/cache/pacman/pkg/gcc-13.2.1-3-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
    Do you want to delete it? [Y/n]
    error: failed to commit transaction (invalid or corrupted package)
    Errors occurred, no packages were upgraded.
    ==> ERROR: 'pacman' failed to install missing dependencies.
    ==> Missing dependencies:
      -> cmake
      -> gcc
      -> ninja
    ==> ERROR: Could not resolve all dependencies.

Fix this by updating archlinux:base and rebuilding the Docker image.

Updating exposed another issue. The built image contains a lock file,
and that lock file causes GnuPG to hang. Work around the hang by
deleting the lock file from the image.