fix(port): fix 'environ' undeclared on FreeBSD
FreeBSD, Linux, and other POSIX platforms require that you declare
'environ' yourself. (However, we were getting lucky on Linux because
glibc declares environ for us if _GNU_SOURCE is set.) Currently,
building on FreeBSD fails:

    [snip]/child-process.cpp:132:36: error: use of undeclared identifier 'environ'

Explicitly declare 'environ', fixing the build on FreeBSD.

Co-Authored-By: Nico Sonack <nsonack@herrhotzenplotz.de>