fix(vscode): fix flaky CI
Our macOS x86_64 builds are flaky, often failing with the following
output:

    yarn run v1.22.19
    warning quick-lint-js@2.6.0: The engine "vscode" appears to be invalid.
    $ node test/run-vscode-tests.js --target darwin-x64
    node:events:505
          throw er; // Unhandled 'error' event
          ^
    Error: read ECONNRESET
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
    Emitted 'error' event on ClientRequest instance at:
        at TLSSocket.socketErrorListener (node:_http_client:454:9)
        at TLSSocket.emit (node:events:527:28)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      errno: -54,
      code: 'ECONNRESET',
      syscall: 'read'
    }
    error Command failed with exit code 1.
    Downloading VS Code 1.49.0 from https://update.code.visualstudio.com/1.49.0/darwin/stableinfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

It seems like this issue has been fixed in a newer version of
vscode-test (specifically 2.1.4). I think the commit is 3d7d4dfc [1].
I'm not sure though.

Upgrade vscode-test (renamed to @vscode/test-electron), fixing the CI
flakiness.

[1] https://github.com/microsoft/vscode-test/commit/3d7d4dfcf7167a93d70c064d5ed86919ffe7d97c