Change from C style cast to C++ style cast
Clang 9 libstdc++

error: use of old-style cast [-Werror,-Wold-style-cast]
char* qljs_sublime_text_program_error_reports = (char*)"";
                                                ^      ~~