7$: Error with nice message when trying to use TypeScript-style const fields
- Reporting a `typescript_style_const_error` when a const field is used: 

```
class C {
  const f = null;
}
```

quick-lint-js reported:
```
hello.js:2:3: error: unexpected token [E054]
```

quick-lint-js now reports:
```
a.js:3:3: error: const fields within classes are only allowed in TypeScript, not Javascript [E165]
```


Fixes #235