Enable basic translations of linter errors
I want quick-lint-js's errors to be translatable to other languages.
Make this possible with a few major components:

* Mark error message strings for translation.
* Create infrastructure for managing translation files.
* Detect user's preferred language when running quick-lint-js.
* Look up translations for messages when reporting errors.
* Add a dummy translation as a proof of concept.

Leverage GNU gettext's PO-based tooling for translation files. Implement
the translation runtime ourselves because GNU gettext complicates
deployment.

To use the dummy translation, set the `LANGUAGE` environment variable to
(for example) `en@loud`:

    $ LANGUAGE=en@loud ./build/quick-lint-js hello.js
    hello.js:1:20: error: VARIABLE USED BEFORE DECLARATION: language
    hello.js:2:7: note: VARIABLE DECLARED HERE
    hello.js:3:1: error: ASSIGNMENT TO CONST VARIABLE
    hello.js:1:7: note: VARIABLE DECLARED HERE