Fix compilation on macOS; add missing #include
Compiling quick-lint-js fails on macOS with the following error:

    ../src/lex.cpp:668:7: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const char *')
    [snip]/type_traits:4050:3: note: candidate function template not viable: cannot convert argument of incomplete type 'std::ostream' (aka 'basic_ostream<char>') to 'std::byte' for 1st argument
    ../src/lex.cpp:667:15: note: candidate function not viable: no known conversion from 'const char *' to 'quick_lint_js::token_type' for 2nd argument
    [snip]/memory:5018:1: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-2>' against 'const char *'
    [snip]/string_view:774:1: note: candidate template ignored: could not match 'basic_string_view<type-parameter-0-0, type-parameter-0-1>' against 'const char *'

Fix this error by defining the needed operator<< overload via <ostream>.