feat: improve error for missing semicolon in classes
    class C {
        a = 42 b
    }

before:

    hello.js:2:9: error: missing semicolon after statement [E0027]

after:

    hello.js:2:9: error: missing semicolon after field [E0223]