Show declaration of variables in error messages
If a variable is used before its declaration, and we report an error,
include the location of the declaration in additition to the variable's
use:

    console.log(x);
    let x = "hello";

    hello.js:1:13: error: variable used before declaration: x
    hello.js:2:5: note: variable declared here