fix(port): add missing #include
Fix the following build error on newer Ubuntu:

```
src/quick-lint-js/port/thread-name.cpp:41:55: error: ‘uintptr_t’ in namespace ‘std’ does not name a type
   41 |   int rc = ::prctl(PR_SET_NAME, reinterpret_cast<std::uintptr_t>(new_name_cstr),
      |                                                       ^~~~~~~~~
```