npm: Fix installation with Yarn
Installing quick-lint-js with Yarn has a few problems:

1. Installing does not generate a symlink in node_modules/.bin/.
2. Installing twice explicitly crashes:

    $ yarn add quick-lint-js
    [snip]
    $ yarn add quick-lint-js
    [snip]
    error [snip]/node_modules/quick-lint-js: Command failed.
    Exit code: 1
    Command: node preinstall.js
    Arguments:
    Directory: [snip]/node_modules/quick-lint-js
    Output:
    internal/fs/utils.js:269
        throw err;
        ^

    Error: EEXIST: file already exists, copyfile '[snip]/node_modules/quick-lint-js/linux/bin/quick-lint-js' -> '/home/strager/Projects/quicklint-js/testnpm/node_modules/quick-lint-js/quick-lint-js.exe'
        at Object.copyFileSync (fs.js:1907:3)
        at Object.<anonymous> ([snip]/node_modules/quick-lint-js/preinstall.js:35:4)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
        at internal/main/run_main_module.js:17:47 {
      errno: -17,
      syscall: 'copyfile',
      code: 'EEXIST',
      path: '[snip]/node_modules/quick-lint-js/linux/bin/quick-lint-js',
      dest: '[snip]/node_modules/quick-lint-js/quick-lint-js.exe'
    }
    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

It looks like these problems are caused by Yarn behaving differently
from npm. Fix these problems with some careful workarounds.