fix(port): fix bad reference to 'environ' global
We forward-declare 'environ' on Linux. However, our forward declaration is
inside a namespace, and that seems to cause problems on Arch Linux now:

```
/usr/sbin/ld: ../src/libquick-lint-js-lib.a(child-process.cpp.o): warning: relocation against `_ZN13quick_lint_js12_GLOBAL__N_17environE' in read-only section `.text._ZN13quick_lint_js12_GLOBAL__N_1L21get_posix_environmentEv'
/usr/sbin/ld: ../src/libquick-lint-js-lib.a(child-process.cpp.o): in function `quick_lint_js::(anonymous namespace)::get_posix_environment()':
/__w/quick-lint-js/quick-lint-js/src/quick-lint-js/port/child-process.cpp:364:(.text._ZN13quick_lint_js12_GLOBAL__N_1L21get_posix_environmentEv+0x7): undefined reference to `quick_lint_js::(anonymous namespace)::environ'
/usr/sbin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

Fix this issue by moving the forward declaration of 'environ' out of a
namespace.